name: .NET Tests with MSTest

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the solution
      run: dotnet build --no-restore

    - name: Run tests in Payload Ops Tests project
      run: dotnet test "Payload Ops Tests/Payload Ops Tests.csproj" --filter "FullyQualifiedName~Payload_Ops_Tests" --collect:"XPlat Code Coverage" --results-directory ./TestResults/PayloadOps

    - name: Run tests in Uplink Downlink Tests project
      run: dotnet test "Tests/Uplink Downlink Tests.csproj" --filter "FullyQualifiedName~Uplink_Downlink_Tests" --collect:"XPlat Code Coverage" --results-directory ./TestResults/UplinkDownlink

    - name: Display coverage results
      run: grep 'line-rate' ./TestResults/*/coverage.cobertura.xml
