name: .NET Tests with MSTest

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'
        
    - name: Install grep (if needed)
      run: sudo apt-get update && sudo apt-get install -y grep
  
    - name: Restore dependencies
      run: dotnet restore

    - name: Build the solution
      run: dotnet build --no-restore

    - name: Run Payload Ops Tests
      run: dotnet test "Payload Ops Tests/Payload Ops Tests.csproj" --filter "FullyQualifiedName~Payload_Ops_Tests"  --collect:"XPlat Code Coverage" --results-directory ./TestResults
      
    - name: Display Payload Ops Tests Coverage
      run: |
        run: grep 'line-rate' ./TestResults/*/coverage.cobertura.xml

