name: .NET Tests with MSTest

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the solution
      run: dotnet build --no-restore

    - name: Run Payload Ops Tests
      run: dotnet test "Payload Ops Tests/Payload Ops Tests.csproj" --collect:"XPlat Code Coverage" --results-directory ./TestResults/PayloadOps
    - name: List files in PayloadOps test results
      run: | 
       find ./TestResults/PayloadOps/
    
    - name: Display Payload Ops Tests Coverage
      run: |
        grep "linerate=" ./TestResults/PayloadOps/**/coverage.cobertura.xml
    
    - name: Run Uplink Downlink Tests
      run: dotnet test "Uplink Downlink Tests/Uplink Downlink Tests.csproj" --collect:"XPlat Code Coverage" --results-directory ./TestResults/UplinkDownlink

    - name: Display Uplink Downlink Tests Coverage
      run: |
        grep "linerate=" ./TestResults/UplinkDownlink/**/coverage.cobertura.xml
